hoppscotch/docs

content/en/features/authorization.md, content/en/features/pre-request-script.md, content/en/features/request.md, content/en/index.md, content/en/quickstart/graphql.md, content/en/quickstart/mqtt.md, content/en/quickstart/rest.md
added spaces after commas across the docs for consistent typography
=> added spaces after commas

content/en/develop.md, content/en/i18n.md
=> Updated develop.md

content/en/develop.md, content/en/index.md, content/en/quickstart/rest.md
=> (#40) Fix casing of GitHub

README.md, content/en/features/authorization.md, content/en/features/body.md, content/en/features/environments.md, content/en/features/headers.md, content/en/features/tests.md, content/en/features/translations.md, content/en/index.md, content/en/quickstart/graphql.md, content/en/quickstart/mqtt.md, content/en/quickstart/rest.md, content/en/quickstart/scripts.md, content/en/quickstart/sse.md, content/en/quickstart/tests.md, content/en/rest.md
Fix spacing or spelling across repository.
=> Fixing Misspellings Across Documentation

content/en/features/tests.md
Little mistake in the doc. :+1:
=> fix nuxt link

content/en/features/authorization.md
=> Updating broken images link.

content/en/features/body.md
=> fix: broken link

content/en/quickstart.md
Minor typos and grammatical errors fixed in quickstart.md.
=> Typos fixed in quickstart.md

content/en/features/collections.md
=> update link on collections.md

content/en/features/translations.md
Updating broken link translations.md
Closes #89
=> Updating broken link

content/en/features/authorization.md, content/en/features/collections.md, content/en/features/translations.md
Fixes production images that isn't showing correctly, with this fix the relatives paths are setted correctly.
=> fix: set relative path to production /static/ path correctly

content/1.documentation/5.self-host/1.prerequisites.md
Closes # 
This PR introduces additions to the following topics:
- Suggesting users to use the right Docker-Compose version
- Suggesting users to issue TLS certificates as we use HTTP, secure cookies
=> chore: update backend related sections in docs 

content/1.documentation/5.self-host/2.install-and-build.md
- add content on accesing hoppscotch
=> chore: update docs

content/0.index.md
- changed the icon for safe and secure
- updated the description
=> updated index page content

content/1.documentation/1.getting-started/4.rest/0.creating-a-request.md
- several endpoints instead of three endpoints
- wording changed a bit
=> The json listed more than 3 endpoints i changed the wording

content/1.documentation/4.features/7.scripts.md
Resolves #130 by adding a relevant example of how to accomplish this need
=> Provide example to save payload values as env vars

content/1.documentation/5.self-host/1.community-edition/1.prerequisites.md, content/1.documentation/5.self-host/1.community-edition/2.install-and-build.md, content/1.documentation/5.self-host/2.enterprise-edition/1.prerequisites.md, content/1.documentation/5.self-host/2.enterprise-edition/2.install-and-build.md
This PR introduces the documentation updated for the following:
* Subpath based access
* Updated container run commands
* Description of new support for standard HTTP/s ingress ports.
=> docs: added additions to docs for dec 2023 release

documentation/features/authorization.mdx, documentation/features/cookies.mdx, documentation/features/oauth2.mdx, documentation/features/variables.mdx, documentation/self-host/enterprise-edition/admin-dashboard.mdx, documentation/self-host/enterprise-edition/install-and-build.mdx, documentation/self-host/enterprise-edition/prerequisites.mdx, mint.json
Added the following-
1. Variables Page defining variable scopes.
2. Edited the existing Authorization page for OAuth 2.0 and added a page for better description of its grant types.
3. Domain and Site Protection access controls in Admin Dashboard for Enterprise.
4. GitHub Enterprise and OIDC Configurations.
=> added documentation updates for Release v2024.3.0

documentation/self-host/community-edition/install-and-build.mdx, documentation/self-host/enterprise-edition/install-and-build.mdx
=> Revert "Updated env file for community and enterprise edition"

documentation/self-host/community-edition/install-and-build.mdx, documentation/self-host/enterprise-edition/install-and-build.mdx
=> Updated the environment variables

documentation/features/widgets.mdx, documentation/features/workspaces.mdx, documentation/self-host/community-edition/install-and-build.mdx, documentation/self-host/enterprise-edition/install-and-build.mdx
=> added ALLOW_SECURE_COOKIES env variable & made minor changes to docs

documentation/self-host/community-edition/admin-dashboard.mdx, documentation/self-host/enterprise-edition/admin-dashboard.mdx
This PR contains addition to following features related to Release 2024.7.0
=> Added User Management APIs and Infra-tokens for Release 2024.7.0

documentation/clients/cli/overview.mdx, documentation/features/collections.mdx, documentation/self-host/community-edition/admin-dashboard.mdx, documentation/self-host/enterprise-edition/admin-dashboard.mdx
This PR includes all the latest updates from Release v2024.7.0:
=> Release v2024.7.0

documentation/self-host/community-edition/admin-dashboard.mdx
This PR adds a subsection to the InfraTokens section about "How to Use InfraTokens".
=> How to use InfraTokens section

documentation/features/importer.mdx
=> Added check-mark for insomnia environment import

documentation/features/context-menu.mdx, mint.json
Created a completed guide for context-aware-menus with well-explained and covered all the options including 
- Set as variable
- Add to parameters 
- Open req in a new tab
Need reviews - @SanskritiHarmukh @thetronjohnson
=> Added guide for context-menu

README.md
Solves issue #227 
Updated the readme.md file with new changes and added instructions required to set up the Hoppscotch docs repo on local development. 
Added warning message to the readme.
Need review - @thetronjohnson @SanskritiHarmukh @liyasthomas
=> added instruction to readme file with Node version requires for mintlify

documentation/self-host/community-edition/install-and-build.mdx, documentation/self-host/enterprise-edition/admin-dashboard.mdx, documentation/self-host/enterprise-edition/install-and-build.mdx
This PR include following updates:
=> v2024.8.0 Documentation Updates: Workspace Management APIs and DATA_ENCRYPTION_KEY env variable

documentation/features/authorization.mdx, documentation/features/importer.mdx, documentation/getting-started/rest/request-headers.mdx, documentation/getting-started/rest/request-parameters.mdx, documentation/self-host/community-edition/install-and-build.mdx, documentation/self-host/enterprise-edition/admin-dashboard.mdx, documentation/self-host/enterprise-edition/install-and-build.mdx, mint.json
This PR includes documentation updates for our major release, v2024.8.0:
=> Release v2024.8.0 Documentation Updates

guides/articles/self-host-hoppscotch-on-your-own-servers.mdx
=> Updated the .env file with DATA_ENCRYPTION_KEY

documentation/features/client-certificate.mdx
=> Updated description of Client Certificates Page

guides/articles.mdx, guides/articles/self-host-hoppscotch-on-your-own-servers.mdx
=> Made minor changes in guides section

documentation/features/authorization.mdx, documentation/features/importer.mdx
This PR accounts for following updates:
=> Revamping Authorization page and adding needed details related to callback URL in OAuth flow

documentation/self-host/community-edition/admin-dashboard.mdx, documentation/self-host/enterprise-edition/admin-dashboard.mdx, documentation/self-host/enterprise-edition/install-and-build.mdx
This PR includes documentation additions related to following:
=> v2024.10.0: Add documentation for horizontal scaling related variables and the new User Management API

documentation/self-host/enterprise-edition/install-and-build.mdx
This PR accounts for following changes:
=> Update the key of horizontal scaling variable

documentation/features/authorization.mdx, documentation/features/importer.mdx, documentation/self-host/community-edition/admin-dashboard.mdx, documentation/self-host/community-edition/install-and-build.mdx, documentation/self-host/enterprise-edition/admin-dashboard.mdx, documentation/self-host/enterprise-edition/install-and-build.mdx
This PR includes documentation updates for Release v2024.10.0. It covers the following updates that have been reviewed in PRs #253 , #254 , #255 , #256 :
=> Release v2024.10.0 documentation additions

documentation/features/client-certificate.mdx
=> docs: updated the client certificate page

documentation/features/runner.mdx, documentation/getting-started/graphql/creating-a-query.mdx, documentation/getting-started/graphql/using-variables.mdx, documentation/getting-started/rest/tests.mdx, documentation/getting-started/rest/uploading-data.mdx, documentation/self-host/community-edition/admin-dashboard.mdx, documentation/self-host/enterprise-edition/admin-dashboard.mdx, documentation/self-host/enterprise-edition/install-and-build.mdx
**This PR includes the Release `v2024.12.0` documentation additions:**
**Minor Changes:**
=> Release v2024.12.0 Documentation additions

documentation/features/interceptor.mdx
This PR introduces installation and setup instructions for using Proxyscotch.
=> add: proxyscotch setup instructions

documentation/features/variables.mdx
Add collection variable details in variable page and add variable priority list
=> chore: add coll variable and priority list
