hoppscotch/docs

- content/en/features/pwa.md
Fixed a typo (`paltform` -> `platform`) and made a couple other small grammatical improvements.
Thanks for this great app!
> pwa.md typo and other small improvements

- content/en/quickstart/tests.md
The wrong word, which sounded similar, was used.
> Proper use of Accepts instead of Excepts

- content/2.guides/2.articles/5.audit-logs.md
In this PR, the `Tracked Events` table in the `Audit Logs` guide has been fully populated with all the events that we currently log into `Clickhouse`.
> chore: populated tracked events in Audit Log guide

- content/1.documentation/5.self-host/2.enterprise-edition/2.install-and-build.md
In this PR I am introducing a fix in the `Install and Build` section on the Enterprise docs.
> fix: fixed incorrect container used in enterprise section

- content/1.documentation/1.getting-started/6.realtime/3.mqtt.md
Fix a typo on the `MQTT` page.
> docs(realtime): fix typo

- content/1.documentation/5.self-host/1.community-edition/1.prerequisites.md
- content/1.documentation/5.self-host/2.enterprise-edition/1.prerequisites.md
Adjust the auth provider callback urls according to the callback url pattern with `/v1/`. It was missing for the Github callback urls.
Pattern:
`http://localhost:3170/v1/auth/[auth_provider_name]/callback`
> docs: adjust callback url according to the callback url pattern

- content/1.documentation/5.self-host/1.community-edition/2.install-and-build.md
- content/1.documentation/5.self-host/2.enterprise-edition/2.install-and-build.md
In this PR we have added details on what users need to do when they encounter a database docker exec -it container_id bash issue.
> chore: added migration error to migration section

- content/1.documentation/2.clients/2.cli.md
The minimum supported Node.js version for the CLI was bumped to `v18` in https://github.com/hoppscotch/hoppscotch/pull/3441. This PR adds a note about the same in the docs.
Closes HP-176.
> docs(cli): mention the minimum supported Node.js version

- documentation/self-host/community-edition/install-and-build.mdx
- documentation/self-host/enterprise-edition/install-and-build.mdx
- package-lock.json
In this PR we are adding the following missing `ENABLE_SUBPATH_BASED_ACCESS` variable into the self-host documentation pages.
> Adding missing subpath env varible in the docs

- documentation/self-host/community-edition/admin-dashboard.mdx
- documentation/self-host/enterprise-edition/admin-dashboard.mdx
This PR includes the following additions and improvements for both the Community and Enterprise Edition's Admin Dashboard page:
> Added a new route to DELETE an existing user

- documentation/self-host/community-edition/prerequisites.mdx
- documentation/self-host/enterprise-edition/prerequisites.mdx
This PR includes an addition to the [Email Delivery section of the Prerequisites page](https://docs.hoppscotch.io/documentation/self-host/community-edition/prerequisites#email-delivery):
> Added documentation for custom-smtp configuration

- guides/articles/improving-your-api-workflow.mdx
- guides/articles/self-host-hoppscotch-on-your-own-servers.mdx
- mint.json
This PR contains the following:
> Added a guide for Self-Hosting Hoppscotch

- documentation/features/authorization.mdx
- documentation/features/importer.mdx
- documentation/getting-started/rest/request-headers.mdx
- documentation/getting-started/rest/request-parameters.mdx
- mint.json
This PR includes documentation related to the following:
> v2024.8.0 Documentation Updates: AWS Signature Auth Method, Description field, Import HAR files

- documentation/self-host/community-edition/install-and-build.mdx
- documentation/self-host/enterprise-edition/install-and-build.mdx
> Warning note related to Breaking change in Self-Hosted Edition

- documentation/features/workspaces.mdx
> Note on limitations of shared workspaces with GraphQL APIs.

- documentation/self-host/enterprise-edition/install-and-build.mdx
With v2024.9.2, Hoppscotch Enterprise Edition instances will support pulling additional user info from SAML authentication flows. This PR intends to documentation text to clear the info around that.
> feat: info about SAML configurations

- documentation/self-host/community-edition/install-and-build.mdx
- documentation/self-host/enterprise-edition/install-and-build.mdx
This PR intends to add a section explaining the ability for AIO containers to bind to non privileged ports and the `HOPP_AIO_ALTERNATE_PORT` variable.
> feat: explain `HOPP_AIO_ALTERNATE_PORT` variable and its uses

- guides/articles/self-host-hoppscotch-on-your-own-servers.mdx
> docs: update the self-host guide with a new variable (`HOPP_AIO_ALTERNATE_PORT`)

- documentation/features/importer.mdx
This PR includes the following:
> docs: update the importer page with additional data imported from each source

- documentation/self-host/community-edition/admin-dashboard.mdx
- documentation/self-host/enterprise-edition/admin-dashboard.mdx
This PR includes the following changes in the Self-Hosted Community and Enterprise edition docs:
> docs: update user management section with invite flow and pending invite

- documentation/clients/cli/overview.mdx
This PR updates the documentation to reflect the change in the minimum supported Node.js version for the Hoppscotch CLI. The minimum supported version is now **v20**, with continued support for Node.js v18 until April 2025 using CLI `v0.11.1`.
> Update: Minimum Supported Node.js Version for CLI (v20)

- documentation/self-host/enterprise-edition/install-and-build.mdx
This PR adds a new optional attribute (`isAdmin`) to the SAML Configuration settings. It also includes a table that explains the format and values for this attribute, making it easier to understand how to use it.
> update: add a new "isAdmin" attribute to the SAML configuration settings.

- documentation/self-host/community-edition/admin-dashboard.mdx
- documentation/self-host/enterprise-edition/admin-dashboard.mdx
This PR introduces a new section for configuring the Request History settings from the Admin Dashboard on both self-hosted editions, along with some minor fixes.
> update: add history configuration details on Admin Dashboard

- documentation/community.mdx
- documentation/features/ai-experiments.mdx
- documentation/features/ai-features.mdx
- mint.json
This PR introduces a dedicated page for AI Experiments. It outlines the steps to enable AI-powered functionality across Hoppscotch and provides details on how to use these features.
Plus, updated the Twitter logo to the new X logo.
> docs: add a page for AI-powered features

- documentation/self-host/community-edition/admin-dashboard.mdx
- documentation/self-host/enterprise-edition/admin-dashboard.mdx
Since the Swagger documentation hosted at staging instances is no longer maintained, this update revises the note to clearly guide users on how to access the User Management and Workspace Management APIs directly through the `/api-docs` endpoint.
> update: revised note on accessing User and Workspace Management APIs

- documentation/features/authorization.mdx
This PR adds a note about the newly introduced support for selecting the client credentials delivery method (Body or Basic Auth) using `Client Authentication` in the Client Credentials OAuth 2.0 flow.
> update: Client Authentication field within Client Credentials

- documentation/self-host/getting-started.mdx
- documentation/self-host/helm-chart-deployment/digital-ocean.mdx
- documentation/self-host/helm-chart-deployment/getting-started.mdx
- mint.json
This PR caters to Helm chart instructions that can be used for deploying a self-hosted Hoppscotch instance on Kubernetes.
> add: Helm Chart Instructions for Deploying Hoppscotch on Kubernetes
